### ISSUE TITLE
ubuntu 14.10 python3.4

### ISSUE THREAD

**Issue by solarw** [alexcouper/captainhook#76]
pre-commit is autodecting python with /usr/bin/env python and returns python2.7

i hardcoded #!/usr/bin/python3  in pre-commit file

run captainhook run shows nothing. no errors. with python2.7 it shows errors about import errors

looks like it does not work with python3.4

**Comment by alexcouper** [comment]
@solarw thanks for raising this.

Would you be able to provide an example file that had errors when py2.7 was being used but not py3.4?

**Comment by alexcouper** [comment]
The project assumes that you'll be in your virtualenv when committing.

It sounds like you're not - are you using a virtualenv?

If you run ``/usr/bin/env python --version`` you should get a python3.4 back if you are in a python3 virtualenv.

![python3-2](https://cloud.githubusercontent.com/assets/837734/7285303/1c62f3b2-e933-11e4-858a-1ab745dd84dd.gif)

**Comment by alexcouper** [comment]
Closing due to inactivity

**Comment by browniebroke** [comment]
I've had the same issue today, my project is running in a Vagrant, so I don't have virtualenv.

For the record, the traceback was something like:
```shell
> captainhook run
Traceback (most recent call last):
  File "/.../.git/hooks/pre-commit", line 37, in <module>
    from checkers.utils import get_files, HookConfig, get_config_file
  File "/.../.git/hooks/checkers/utils.py", line 12, in <module>
    from bash import bash
ImportError: No module named bash
```

Editing the shebang of `.git/hooks/pre-commit` to `#!/usr/bin/env python3` made the trick. I'm not expecting a fix for that, my comment is merely for documentation purposes.
